services:
  backend-dev:
    build:
      context: .
      target: development
    container_name: eventide-backend-dev
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  backend-prod:
    build:
      context: .
      target: production
    container_name: eventide-backend-prod
    ports:
      - "4000:3000"
    env_file: .env
    restart: unless-stopped
    command: npm run start:prod

  osrm-prepare:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: eventide-osrm-prepare
    profiles: ["maps-prepare"]
    volumes:
      - ./data/osrm:/data
    command: >
      sh -c "osrm-extract -p /opt/car.lua /data/map.osm.pbf &&
      osrm-partition /data/map.osrm &&
      osrm-customize /data/map.osrm"

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: eventide-osrm
    profiles: ["maps"]
    ports:
      - "5000:5000"
    volumes:
      - ./data/osrm:/data
    command: osrm-routed --algorithm mld /data/map.osrm
    restart: unless-stopped
